"""
gen_maps.py
Generates airspace maps for the Drone Pathfinder Challenge.

Every generated map is verified at generation time, so it always has at
least one valid path from S to T. Hard-mode maps are verified further:
every waypoint is reachable, and a route that respects the scorer's risk
cap exists.

Standard practice map:
    uv run gen_maps.py --out maps/practice_maps/my_map.txt --seed 42
    uv run gen_maps.py --out maps/practice_maps/big.txt --height 30 --width 30

Hard-mode practice map (adds weighted airspace + delivery waypoints):
    uv run gen_maps.py --mode hard --out maps/practice_maps/hard/h1.txt --seed 7

A numbered pool at once (--out is a directory when --count > 1):
    uv run gen_maps.py --mode hard --out maps/practice_maps/hard --count 6 --seed 100

Regenerate the stock practice map:
    uv run gen_maps.py

The scoring maps are deliberately NOT generated by the committed defaults -
their parameters live in the instructor-only tooling so they cannot be
reproduced from this file.
"""

import argparse
import random
from collections import deque
from pathlib import Path

from map_utils import wall_count

# (path, height, width, wall_probability, seed) for the stock practice map.
PRACTICE_MAP = ("maps/practice_maps/practice_map.txt", 10, 10, 0.22, 1)

# Cells touching this many '#' are off-limits to the scorer's risk cap; a
# hard map is only accepted if S can still reach every waypoint and T
# without ever stepping on such a cell.
RISK_CAP_WALLS = 3


def bfs_reachable(grid, start):
    h, w = len(grid), len(grid[0])
    seen = {start}
    q = deque([start])
    while q:
        r, c = q.popleft()
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = r + dr, c + dc
            if (
                0 <= nr < h
                and 0 <= nc < w
                and (nr, nc) not in seen
                and grid[nr][nc] != "#"
            ):
                seen.add((nr, nc))
                q.append((nr, nc))
    return seen


def risk_safe_reachable(grid, start):
    """BFS that refuses to enter a cell touching >= RISK_CAP_WALLS walls.

    Mirrors the scorer's risk cap so a hard map is never shipped with a
    waypoint or target that a cap-respecting route cannot reach.
    """
    h, w = len(grid), len(grid[0])
    if wall_count(grid, start) >= RISK_CAP_WALLS:
        return set()
    seen = {start}
    q = deque([start])
    while q:
        r, c = q.popleft()
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = r + dr, c + dc
            if (
                0 <= nr < h
                and 0 <= nc < w
                and (nr, nc) not in seen
                and grid[nr][nc] != "#"
                and wall_count(grid, (nr, nc)) < RISK_CAP_WALLS
            ):
                seen.add((nr, nc))
                q.append((nr, nc))
    return seen


def gen_map(h, w, wall_prob, seed):
    """Generate an h x w standard map with a guaranteed S -> T path."""
    rng = random.Random(seed)
    while True:
        grid = [
            ["#" if rng.random() < wall_prob else "." for _ in range(w)]
            for _ in range(h)
        ]
        start = (0, 0)
        target = (h - 1, w - 1)
        grid[start[0]][start[1]] = "."
        grid[target[0]][target[1]] = "."
        if target in bfs_reachable(grid, start):
            grid[start[0]][start[1]] = "S"
            grid[target[0]][target[1]] = "T"


            return ["".join(row) for row in grid]
    


def _add_terrain(grid, rng, max_weight):
    """Overlay weighted airspace (digits) as a few random 'cost blobs' so
    the weights cluster into detours worth reasoning about rather than
    salt-and-pepper noise."""
    h, w = len(grid), len(grid[0])
    open_cells = [(r, c) for r in range(h) for c in range(w) if grid[r][c] == "."]
    if not open_cells:
        return
    n_blobs = max(2, len(open_cells) // 28)
    for _ in range(n_blobs):
        cr, cc = rng.choice(open_cells)
        radius = rng.randint(1, 3)
        peak = rng.randint(3, max_weight)
        for r in range(max(0, cr - radius), min(h, cr + radius + 1)):
            for c in range(max(0, cc - radius), min(w, cc + radius + 1)):
                if grid[r][c] == "#":
                    continue
                val = peak - (abs(r - cr) + abs(c - cc))
                if val < 2:
                    continue
                cur = grid[r][c]
                cur_val = int(cur) if cur.isdigit() else 1
                grid[r][c] = str(min(max_weight, max(cur_val, val)))


def _pick_waypoints(rng, reachable, start, target, n, min_spacing=3):
    """Choose n reachable cells, spaced apart from each other and from
    S / T so the tour is a real routing problem. Returns [] on failure."""
    candidates = [
        p
        for p in reachable
        if p not in (start, target)
        and abs(p[0] - start[0]) + abs(p[1] - start[1]) >= min_spacing
        and abs(p[0] - target[0]) + abs(p[1] - target[1]) >= min_spacing
    ]
    rng.shuffle(candidates)
    chosen = []
    for p in candidates:
        if all(abs(p[0] - q[0]) + abs(p[1] - q[1]) >= min_spacing for q in chosen):
            chosen.append(p)
        if len(chosen) == n:
            return chosen
    return []


def gen_hard_map(h, w, wall_prob, seed, n_waypoints, max_weight=9):
    """Generate an h x w hard-mode map: weighted airspace plus
    `n_waypoints` mandatory delivery stops, verified feasible."""
    rng = random.Random(seed)
    start = (0, 0)
    target = (h - 1, w - 1)
    for _ in range(4000):
        grid = [
            ["#" if rng.random() < wall_prob else "." for _ in range(w)]
            for _ in range(h)
        ]
        grid[start[0]][start[1]] = "."
        grid[target[0]][target[1]] = "."
        reachable = bfs_reachable(grid, start)
        if target not in reachable:
            continue
        waypoints = _pick_waypoints(rng, reachable, start, target, n_waypoints)
        if not waypoints:
            continue
        _add_terrain(grid, rng, max_weight)
        grid[start[0]][start[1]] = "S"
        grid[target[0]][target[1]] = "T"
        for r, c in waypoints:
            grid[r][c] = "*"
        safe = risk_safe_reachable(grid, start)
        if target not in safe or any(wp not in safe for wp in waypoints):
            continue
        return ["".join(row) for row in grid]
    raise RuntimeError(
        "could not generate a feasible hard map; try a lower --wall-prob "
        "or fewer --waypoints"
    )


def write_map(path, rows):
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    # newline="" keeps LF on Windows too; the repo's pre-commit hooks enforce LF.
    with out.open("w", newline="") as f:
        _ = f.write("\n".join(rows) + "\n")
    print(f"wrote {out} ({len(rows)}x{len(rows[0])})")


def _one_map(args, seed):
    if args.mode == "hard":
        return gen_hard_map(
            args.height, args.width, args.wall_prob, seed, args.waypoints
        )
    return gen_map(args.height, args.width, args.wall_prob, seed)


def main():
    parser = argparse.ArgumentParser(description="Generate airspace maps.")
    parser.add_argument(
        "--out", help="Write a single map here instead of the standard set"
    )
    parser.add_argument(
        "--mode",
        choices=["standard", "hard"],
        default="standard",
        help="hard adds weighted airspace (digits) and '*' delivery waypoints",
    )
    parser.add_argument("--height", type=int, default=12)
    parser.add_argument("--width", type=int, default=12)
    parser.add_argument(
        "--wall-prob", type=float, default=0.25, help="Fraction of '#' cells"
    )
    parser.add_argument(
        "--waypoints",
        type=int,
        default=3,
        help="hard mode: number of mandatory '*' delivery stops (1-4)",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=1,
        help="generate N maps; --out is treated as a directory when N > 1",
    )
    parser.add_argument("--seed", type=int, default=0, help="Same seed = same map")
    args = parser.parse_args()

    if args.out and args.count > 1:
        outdir = Path(args.out)
        outdir.mkdir(parents=True, exist_ok=True)
        for i in range(args.count):
            seed = args.seed + i
            write_map(outdir / f"{args.mode}_{seed:04d}.txt", _one_map(args, seed))
        return

    if args.out:
        rows = _one_map(args, args.seed)
        write_map(args.out, rows)
        print()
        print("\n".join(rows))
        return

    path, h, w, wall_prob, seed = PRACTICE_MAP
    write_map(path, gen_map(h, w, wall_prob, seed))


if __name__ == "__main__":
    main()
